In [118]:
import numpy as np
import time

In [119]:
def print_array(array):
    print(f"array = {array}")
    print(f"array shape = {array.shape}")
    print(f"array data type = {array.dtype}") 

In [120]:
array = np.zeros(4)
print_array(array)

array = [0. 0. 0. 0.]
array shape = (4,)
array data type = float64


In [121]:
array = np.zeros((4,))
print_array(array)

array = [0. 0. 0. 0.]
array shape = (4,)
array data type = float64


In [122]:
array = np.random.random_sample([2,2])
print_array(array)

array = [[0.68680472 0.96967751]
 [0.74324501 0.29691275]]
array shape = (2, 2)
array data type = float64


In [123]:
array = np.arange(5.)
print_array(array)

array = [0. 1. 2. 3. 4.]
array shape = (5,)
array data type = float64


In [124]:
array = np.random.rand(5)
print_array(array)

array = [0.15035416 0.49476419 0.76952018 0.08475613 0.55201978]
array shape = (5,)
array data type = float64


In [125]:
array = np.array([1,2,3,4])
print_array(array)

array = [1 2 3 4]
array shape = (4,)
array data type = int64


In [126]:
array = np.array([1.0,2.0,3,4.])
print_array(array)

array = [1. 2. 3. 4.]
array shape = (4,)
array data type = float64


In [127]:
array = np.arange(4)
print_array(array)
print(f"array[2] = {array[2]}")
try:
    c = array[10]
except Exception as e:
    print(e)

array = [0 1 2 3]
array shape = (4,)
array data type = int64
array[2] = 2
index 10 is out of bounds for axis 0 with size 4


In [128]:
array = np.arange(10)
print_array(array)
print(array[0:4:2])
print(array[:])
print(array[::-1])
print(array[:5:-1])
print(array[1])

array = [0 1 2 3 4 5 6 7 8 9]
array shape = (10,)
array data type = int64
[0 2]
[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6]
1


In [129]:
array = np.array([1, 2, 3, 4])
sum_oper = np.sum(array)
print(sum_oper)

mean = np.mean(array)
print(mean)

negative = -array
print(negative)

exponent = array**2
print(exponent)

10
2.5
[-1 -2 -3 -4]
[ 1  4  9 16]


In [130]:
array_1 = np.array([2,4,6,8])
array_2 = np.array([-4,-6,-8,-10])

product = array_1 * array_2
print(f"product = {product}")

sum = array_1 + array_2
print(f"sum = {sum}")

product = [ -8 -24 -48 -80]
sum = [-2 -2 -2 -2]


In [131]:
array_3 = np.array([1,2])
array_4 = np.array([1,2])

try:
    print(array_3+array_4)
except Exception as e:
    print(e)

[2 4]


In [132]:
array = np.array([2,3])
print(array * 5)

[10 15]


In [133]:
def dot_product(vector_1, vector_2):
    
    product = 0
    
    for i in range(vector_1.shape[0]):
        product += vector_1[i] * vector_2[i] 
    return product

In [134]:
vector_1 = np.array([1,2,3,4])
vector_2 = np.array([1,2,3,4])
product = dot_product(vector_1,vector_2)
print(f'''dot product of vector_1 * vector_2 = {vector_1} * {vector_2} = {product}''')

dot product of vector_1 * vector_2 = [1 2 3 4] * [1 2 3 4] = 30


In [135]:
vector_1 = np.array([1,2,3,4])
vector_2 = np.array([1,2,3,4])
product = np.dot(vector_1,vector_2)
print(f'''dot product of vector_1 * vector_2 = {vector_1} * {vector_2} = {product}''')

dot product of vector_1 * vector_2 = [1 2 3 4] * [1 2 3 4] = 30


In [136]:
a = np.random.rand(10)
b = np.random.rand(10)

start = time.time()
c = np.dot(a, b)
end = time.time()
print(f"np.dot() = {c:.2f} in time {1000*(end-start):.4f}ms")

start = time.time()
c = dot_product(a,b)
end = time.time()
print(f"loop product variation = {c:.2f} in time {1000*(end-start):.4f}ms")
del(a)
del(b)

np.dot() = 2.93 in time 0.1471ms
loop product variation = 2.93 in time 0.1762ms


In [148]:
x = np.array([[1],[2]])
print(f"x.shape = {x.shape}")

w = np.array([1])
print(f"w.shape = {w.shape}")

dot_multiple = np.dot(x[1],w)
print(f"x[1] = {x[1]}")
print(dot_multiple)

x.shape = (2, 1)
w.shape = (1,)
x[1] = [2]
2


In [151]:
a = np.ones((2,2))
b = np.zeros((3,3))
print(f"a = {a}")
print(f"a.shape = {a.shape}")
print(f"b = {b}")
print(f"b.shape = {b.shape}")

c = np.array([1])
print(f"c = {c}")
print(f"c.shape = {c.shape}")

a = [[1. 1.]
 [1. 1.]]
a.shape = (2, 2)
b = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
b.shape = (3, 3)
c = [1]
c.shape = (1,)


In [152]:
a = np.array([[1],[2],[3]])
print(f"a = {a}")

a = np.array([
    [1],
    [2],
    [3]
])
print(f"a = {a}")

a = [[1]
 [2]
 [3]]
a = [[1]
 [2]
 [3]]


In [161]:
a = np.arange(6).reshape(-1,2)
print(f"a = {a}")
print(f"a[0,1] = {a[0,1]}")
print(f"type(a[0,1]) = {type(a[0,1])}")
print(f"type(a[0]) = {type(a[0])}")

a = [[0 1]
 [2 3]
 [4 5]]
a[0,1] = 1
type(a[0,1]) = <class 'numpy.int64'>
type(a[0]) = <class 'numpy.ndarray'>


In [185]:
a = np.arange(20).reshape(-1,10)
print(f"a = {a}")
print(f"a[0,1] = {a[0,1]}, a[0,1].shape = {a[0,1].shape}")
print(f"a[0,1] = {a[0]}, a[0].shape = {a[0].shape}")
print(f"a[0,1] = {a[:,1]}, a[:,1].shape = {a[:,1].shape}")
print(f"a[0,1] = {a[0,:]}, a[0,:].shape = {a[0,:].shape}")
print(f"a[:,2:7:4] = {a[:,2:7:4]}, a[:,2:7:4].shape = {a[:,2:7:4].shape}")


a = [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0,1] = 1, a[0,1].shape = ()
a[0,1] = [0 1 2 3 4 5 6 7 8 9], a[0].shape = (10,)
a[0,1] = [ 1 11], a[:,1].shape = (2,)
a[0,1] = [0 1 2 3 4 5 6 7 8 9], a[0,:].shape = (10,)
a[:,2:7:4] = [[ 2  6]
 [12 16]], a[:,2:7:4].shape = (2, 2)
